server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: datn
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/datn
    username: postgres
    password: vanh21
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vananh21242004@gmail.com
    password: awwg zipv fdju mzdj
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

application:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_SECRET:your_secure_generated_key}
        token-validity-in-seconds: 2592000
        token-validity-in-seconds-for-remember-me: 2592000
        refresh-token-validity-in-seconds: 2592000
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
