spring:
  application:
    name: datn
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/datn
    username: postgres
    password: vanh21
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vananh21242004@gmail.com
    password: Nguyenthivananh2101@
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug  # Hiển thị câu SQL để debug dễ hơn
        type.descriptor.sql: trace  # Hiển thị giá trị tham số SQL

application:
  security:
    authentication:
      jwt:
        base64-secret: OhWwNOhKThUZT+0VUVfQyx6aJWcScDSecgPHfazq1XAMeckjJg+Yj8Guu1SaXH3bFpmbwlcqzFWLMWnAIhSsCz3EXytY1x3aBA07XQBwVNGAes/OD7BQYLIXmFdwCGdUFXHn0IgapXRQWCRWTLq1f/ZB9xUsnObY9CqLE1nPk46eD355MqwvDHMU5Lbd19/dFCFHlVS58xEE6AbudAnZpii65UTGVrcIIyNKmyM36238s98dY8TpqrejcMqttrn+xZnKyylG0it2HDo1JcdiqtNNlwnn/rbqiOtbKcRMetrOeoR6NEKKBmo33kX89dOzQVXwHaORxv8VdjOPzB0ilQ==
        token-validity-in-seconds: 2592000
        token-validity-in-seconds-for-remember-me: 2592000
        refresh-token-validity-in-seconds: 2592000
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
springdoc:
  swagger-ui:
    tags-sorter: alpha