import type { Metadata } from "next";
import { Lato, Quicksand } from "next/font/google";
import Header from "@/layout/Header";
import Footer from "../layout/Footer";
import "./globals.css";

const lato = Lato({
  subsets: ["latin"],
  variable: "--font-lato",
  weight: ["400", "700"],
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Bicycle Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lato.variable} ${quicksand.variable} antialiased container overflow-x-hidden `} >
        <Header/>
        {children}
        <Footer />
      </body>
    </html>
  );
}
