const productData = [
  {
    id: 1,
    name: "All Natural Italian-Style Chicken Meatballs",
    imageUrl:
      "https://giant.vn/wp-content/uploads/2020/07/talon-1-2021-front-3.jpg",
    rating: 5,
    originalPrice: 2.8,
    discountedPrice: 2.51,
    weight: "500 gram",
    brand: "Hodo Foods",
    type: "NEW",
    textType: "HOT",
  },
  {
    id: 2,
    name: "All Natural Italian-Style Chicken Meatballs",
    imageUrl: "https://giant.vn/wp-content/uploads/2021/11/talon-5-2022.jpg",
    rating: 5,
    originalPrice: 2.8,
    discountedPrice: 2.51,
    weight: "500 gram",
    brand: "Hodo Foods",
    type: "HOT",
    textType: "HOT",
  },
  {
    id: 3,
    name: "All Natural Italian-Style Chicken Meatballs",
    imageUrl: "https://giant.vn/wp-content/uploads/2021/10/talon-4-2022-5.jpg",
    rating: 5,
    originalPrice: 2.8,
    discountedPrice: 2.51,
    weight: "500 gram",
    brand: "Hodo Foods",
    type: "HOT",
    textType: "HOT",
  },
  {
    id: 4,
    name: "All Natural Italian-Style Chicken Meatballs",
    imageUrl: "https://somings.vn/wp-content/uploads/2022/03/lin-51-1.png",
    rating: 3,
    originalPrice: 2.8,
    discountedPrice: 2.51,
    weight: "500 gram",
    brand: "Hodo Foods",
    type: "HOT",
    textType: "HOT",
  },
  {
    id: 5,
    name: "All Natural Italian-Style Chicken Meatballs",
    imageUrl:
      "https://xedaphocsinh.vn/image/THongNhat2023/XedapHocsinh-thong-nhat-mtb-26-02-xanh-720x480.jpg",
    rating: 5,
    originalPrice: 2.8,
    discountedPrice: 2.51,
    weight: "500 gram",
    brand: "Hodo Foods",
    type: "SALE",
    textType: "50%",
  },
];
export default productData;
